name: Weekly F1.5 Standings Update

on:
  schedule:
    # This runs at 09:00 UTC every Monday
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # This adds a "Run now" button in GitHub so you can test it manually

jobs:
  update_standings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install fastf1 pandas

      - name: Run Standings Script
        run: python F1P5_Standings.py  # Make sure this matches your filename!

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.csv *.txt
          git commit -m "Automated F1.5 Standings Update" || exit 0
          git push